### ISSUE TITLE
add mate desktop support and dark theme variant

### ISSUE THREAD

**Issue by morealaz** [chekavy/cheser-icon-theme#53]
in mate desktop, panel show gnome icon instead of mate for application menu
can you make it correct to show mate icon or better make theme desktop environment neutral.
it would be nice to support mate in your great theme and have a dark variant for dark desktop themes.

![screenshot](https://cloud.githubusercontent.com/assets/2796369/10579806/28561a14-7687-11e5-8223-000bc9796662.png)

![screenshot-1](https://cloud.githubusercontent.com/assets/2796369/10579846/51cdca68-7687-11e5-8591-e4ea70c8dcd7.png)

**Comment by chekavy** [comment]
Hi!
I have no time to support others DEs or Distributions. I can support only **last Fedora release with GNOME & Xfce** (I'm using Fedora with GNOME & Xfce).
That's why I can't make icon theme desktop environment neutral, as you ask.

But if you want, you can do:
* remove or replace `start-here` gnome icons
* fork Cheser Icon Theme and change / add / replace icons as you wish
